FollowMechanism/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('my_app.urls'))
]

my_app/urls.py
from django.urls import path

from . import views

app_name = 'my_app'

urlpatterns = [
    path('', views.home_view, name='home_view'),
    path('profile/<int:_id>', views.profile_view, name='profile_view'),
]

my_app/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.

class Profile(models.Model):
    # Each user will have exactly one profile or vice-versa
    owner = models.OneToOneField(User, on_delete=models.CASCADE)

    # A profile can follow multiple account and can be followed by multiple accounts at the same time, that's why
    # we've used M2M field. The related_name attribute specifies the name of the reverse relation.

    # here, self means that the model has an M2M relation with itself
    following = models.ManyToManyField('self', related_name='followed_by', symmetrical=False, blank=True)

    class Meta:
        verbose_name_plural = 'Profiles'

    def __str__(self):
        return f'{self.owner.username}'

my_app/views.py
from django.shortcuts import render, redirect

from .models import Profile


# Create your views here.
def home_view(request):
    profile_list = Profile.objects.all()
    return render(request, 'index.html', {'profile_list': profile_list})


def profile_view(request, _id):
    fetch_profile = Profile.objects.get(id=_id)
    user_profile = request.user.profile

    followers = fetch_profile.followed_by.count() - 1  # omitting self
    following = fetch_profile.following.count() - 1  # omitting self

    if request.method == 'POST':
        action = request.POST.get('follow_unfollow')
        if action == 'follow':
            user_profile.following.add(fetch_profile)
        else:
            user_profile.following.remove(fetch_profile)
        return redirect('my_app:profile_view', fetch_profile.id)
        # return redirect(request, 'my_app:profile_view', _id=fetch_profile.id)

    context = {'fetch_profile': fetch_profile, 'user_profile': user_profile, 'followers': followers,
               'following': following}
    return render(request, 'profile.html', context)

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>All profile's list</title>
</head>
<body>
<h1>Profile's list</h1>
<h2><a href="{% url 'my_app:profile_view' request.user.id %}">My Profile</a></h2>
<ul>
    {% for ele in profile_list %}
        {# we removed our profile from the profile list. As the list is meant for new profiles to be followed  #}
        {% if ele.owner == request.user %}
            {{ continue }}
        {% else %}
            <li><a href="{% url 'my_app:profile_view' ele.id %}">{{ ele }}</a></li>
        {% endif %}
    {% endfor %}
</ul>
<br>
</body>
</html>

templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ fetch_profile.owner.username }}'s profile page</title>
</head>
<body>
    <h2><a href="{% url 'my_app:home_view' %}">Home</a></h2>
    <h1>{{ fetch_profile.owner.username }}</h1>
    <p>followers : {{ followers }} following : {{ following }}</p>
    <h2>followed by :</h2>
    <ul>
        {% for followers in fetch_profile.followed_by.all %}
            {# removing self profile from the follower's list #}
            {% if followers == fetch_profile %}
                {{ continue }}
            {% else %}
                <li>{{ followers }}</li>
            {% endif %}
        {% endfor %}
    </ul>
    <h2>following :</h2>
    <ul>
        {% for following in fetch_profile.following.all %}
            {# removing self profile from the following's list #}
            {% if following == fetch_profile %}
                {{ continue }}
            {% else %}
                <li>{{ following }}</li>
            {% endif %}
        {% endfor %}
    </ul>
    <form action="{% url 'my_app:profile_view' fetch_profile.id %}" method="post">
        {% csrf_token %}
        {% if user_profile in fetch_profile.followed_by.all and user_profile != fetch_profile %}
            {# the 'and' statement is written to hide follow and unfollow buttons from my own profile #}
            <button name="follow_unfollow" value="unfollow">Unfollow</button>
        {% elif user_profile not in fetch_profile.followed_by.all and user_profile != fetch_profile %}
            <button name="follow_unfollow" value="follow">Follow</button>
        {% endif %}
    </form>
</body>
</html>